trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
    - repository: templates
      type: github
      ref: refs/tags/1.1.47
      name: statisticsnorway/azure-pipelines-templates
      endpoint: github-Statistikkbanken

steps:
  - template: docker/docker-build-image-and-push-to-gcr.yml@templates
    parameters:
      imageName: eu.gcr.io/prod-bip/ssb/statbank/pxapi2
      repoName: prod-bip/ssb/statbank/pxapi2
      skipImageVulnerabilityScan: false
      gcrServiceConnection: gcrServiceConnection-Statistikkbanken
